### ISSUE TITLE
Wait on dbt Core PR to change working directory for profiles

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/jaffle_shop_duckdb#12]

**Comment by sungchun12** [comment]
https://github.com/dbt-labs/dbt-core/issues/5411

**Comment by sungchun12** [comment]
https://github.com/dbt-labs/dbt-core/tree/main/docs/arch

**Comment by dbeatty10** [comment]
Here's the custom version of Core we are using in the meantime:
- https://github.com/dbt-labs/jaffle_shop_duckdb/blob/c4caded3ce50991144e8d685e2fded8fefad5bbb/requirements.txt#L7-L9

**Comment by dbeatty10** [comment]
https://github.com/dbt-labs/dbt-core/issues/5411 is included in dbt Core 1.3 🎉
