### ISSUE TITLE
Write new copy for getting started with dbt and duckdb

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/jaffle_shop_duckdb#13]

**Comment by sungchun12** [comment]
My gut tells me this should be self-contained within the README!

**Comment by sungchun12** [comment]
We should show a screenshot of what is possible based on the github actions; show the reader at a glance that this is worth their time.

`dbt build` should run in less than `1 second`

Full Setup should take less than `1 minute`



![Image](https://user-images.githubusercontent.com/19176976/177228891-b4e6b157-1dd5-413e-b84f-962671c3b182.png)



![Image](https://user-images.githubusercontent.com/19176976/177228930-f446a945-57ae-4b92-8b6d-c009ba91ddae.png)

**Comment by dbeatty10** [comment]
Yes, love the idea of showing them why it's worth their time.

Maybe we can circle the 👉 `0.88s` and `42s` 👈  to focus their attention within the screenshot?

**Comment by sungchun12** [comment]
I'm going to open a PR to update the copy of the README! I have headspace to inject juicy updates today.
