### ISSUE TITLE
ADR for Core PR

### ISSUE THREAD

**Issue by sungchun12** [dbt-labs/jaffle_shop_duckdb#15]
https://github.com/dbt-labs/dbt-core/pull/5425

**Comment by sungchun12** [comment]
Waiting for this to be merged before we can ship this under the dbt-labs org

**Comment by sungchun12** [comment]
@dbeatty10 any idea on when this will be merged?

If it's Q3's release, we should default to adding in `export DBT_PROFILES_DIR=$(pwd)` to ensure dbt picks the right `profiles.yml`

**Comment by dbeatty10** [comment]
It would _similar_ to `export DBT_PROFILES_DIR=$(pwd)`, but actually be like this instead:


![Image](https://user-images.githubusercontent.com/44704949/179087905-b4f28114-f125-46a8-875d-118234f7db8f.png)



Not sure if/when it will be merged, but I did present this proposal to the Core team today. The response felt very positive. [Here's the recording](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1657814432048089) for the curious.

In terms of next steps, would probably need formal endorsement from Jeremy Cohen and Leah Antkiewicz for it to be merged.

**Comment by dbeatty10** [comment]
Approved yesterday, but not merged yet.

**Comment by dbeatty10** [comment]
The feature to default to the `profiles.yml` in the current working directory was released in [dbt Core 1.3](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.3) which is [included as a requirement](https://github.com/dbt-labs/jaffle_shop_duckdb/blob/a6ea10d9bd8c6f3803ab1b19a4eb20be494cffc3/requirements.txt#L7-L8) for this repo.
