### ISSUE TITLE
Update README text

### ISSUE THREAD

**Issue by KiraFuruichi** [dbt-labs/jaffle_shop_duckdb#25]
Synced with @sungchun12 on some minor updates to the README to hopefully improve readability :) 

- Linking to documentation on profiles.yml  in step 4
- Removing the "What is a jaffle?" section; I know that's a cornerstone of jaffle shop, but I can't tell if it's just adding dead weight to a semi-long readme
- Moving Doug's callout/dropdown to the virtual environment reactivation earlier up (maybe at the step it occurs)
- The note in [Step 2 here](https://github.com/dbt-labs/jaffle_shop_duckdb#running-build-steps-independently) is potentially confusing—this is bey default using a duckDB database/adapter, so the code should work without having to change any of the model code. I think the note could be reworded along the lines of, "If you decided to use this project in your own data warehouse, make sure....blah blah"
- Linking to documentation on dbt build in step 5

**Comment by sungchun12** [comment]
Yep! After this PR is drafted, I'll dive straight into review!
