### ISSUE TITLE
dbt-duckdb dependency currently points to a branch on a fork

### ISSUE THREAD

**Issue by machow** [dbt-labs/jaffle_shop_duckdb#40]
Hello -- thanks for this repo! I noticed that currently this repo uses code on a fork by @dbeatty10 . 

Are there plans to open a PR and move these changes back into https://github.com/jwills/dbt-duckdb ? It seems like this might be related to https://github.com/jwills/dbt-duckdb/issues/21

**Comment by dbeatty10** [comment]
🎯 Yes, was definitely planning on updating this repo to point back to the real dbt-duckdb once https://github.com/jwills/dbt-duckdb/issues/21 is done!

I was mainly optimizing for not getting a "version out of date!" warning when running `dbt --version` 😅 

So open to the idea of just installing dbt-duckdb>=1.2.0 if that seems more advantageous to you @machow.

**Comment by machow** [comment]
Ahh, looking closer at your branch, I think I'm getting what you're saying. Is it that dbt checks the version of the adaptor, so your change was just to bump the adaptor version (to 1.3+)? Sorry, I thought that maybe other changes had been made in order to support dbt-core 1.3.

I'm loving using this repo to kick the tires with dbt, so can use the checklist in https://github.com/jwills/dbt-duckdb/issues/21 to dig a bit into what on the checklist the adaptor may already have implemented (for example, it appears in the code like the adaptor has support for python models, but I haven't tried it out).

(feel free to close if useful -- I can always post on the adaptor's upgrade issue..!)

**Comment by dbeatty10** [comment]
Yep, you got it -- my change was just to bump the adapter version to 1.3+ -- it didn't make any other changes to support dbt-core 1.3

Status update:
https://github.com/jwills/dbt-duckdb/issues/21 was resolved, [dbt-duckdb 1.3](https://pypi.org/project/dbt-duckdb/#history) was released, and https://github.com/dbt-labs/jaffle_shop_duckdb/pull/41 finished the 1-2-3 punch to get this resolved.
